# Generated by Django 5.0.3 on 2024-04-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login',
            field=models.TimeField(auto_now=True),
        ),
<<<<<<< Updated upstream
    ]
=======
    ]
>>>>>>> Stashed changes
