# Generated by Django 5.0.3 on 2024-04-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_customuser_last_login'),
    ]

    operations = [
    ]
